version: 2

updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "monthly"
      time: "14:00"
      timezone: "America/Sao_Paulo"
    reviewers:
      - "marechal-dev"
