version: "3"

services:
    database:
        image: bitnami/postgresql:15
        container_name: "library-pg-db"
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRESQL_USERNAME=dev_docker
            - POSTGRESQL_PASSWORD=dev_docker
            - POSTGRESQL_DATABASE=library
        volumes:
            - db_data:/data/postgres

    dev:
        build: .
        container_name: "library-api"
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        depends_on:
            - database

volumes:
    db_data:
        driver: local
